[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''s = { "key:s" },'''
position = "after"
payload = '''
h = { "key:h" },
space = { "key:space" },
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "lib/rtf.lua"
pattern = '''if xscale == 0 or yscale == 0 then -- If scale is 0 we can't see the text anyway'''
position = "after"
payload = '''
love.graphics.pop()
-- apparently this was the problem causing more pushs than pops
-- which crashed imgui
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "levelformat/events/Vfx/Deco/deco.lua"
pattern = '''Event.property(event,'decimal','repeatDelay', 'Beats between repeats', {step = cs:getBeatStep(),optional = true, default = 1})'''
position = "after"
payload = '''
if imgui.Button("Open Keyframe Editor ##keyframer") then
	_G.keyframeropen = true
	--cs = bs.load("Keyframer")
	--cs:init(oldcs.level, oldcs.variant, oldcs.editorBeat)
end
'''
match_indent = true

# i don't care anymore
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''function love.update(d)'''
position = "after"
payload = '''
if maininput:pressed("f9") then
	--bbp.utils.printTable(cs.timingInfo)
	--bbp.utils.printTable(cs.preloadSoundData)
end
if _G.keyframeropen then
	local oldcs = helpers.copy(cs)
	_G.keyframeropen = false
	cs = bs.load("Keyframer")
	cs:init(oldcs.level, oldcs.variant, oldcs.editorBeat, oldcs.preloadSoundData and oldcs.preloadSoundData.data or nil)
	--bbp.utils.printTable(oldcs.level)
end
'''
match_indent = true

# ... 2
[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = '''love.graphics.rectangle('fill',0,0,project.res.x,project.res.y)'''
position = "at"
payload = '''
if cs.name ~= 'Keyframer' then
	love.graphics.rectangle('fill',0,0,project.res.x,project.res.y)
else
	local palette = shuv.usePalette and shuv.pal or shuv.paldefault
	
	local bgc = palette[cs.bgColor] or {r=255,g=255,b=255}
	local vc = palette[cs.voidColor] or {r=255,g=255,b=255}
	love.graphics.clear(vc.r/255, vc.g/255, vc.b/255)
	
	love.graphics.setColor(bgc.r/255, bgc.g/255, bgc.b/255)
	love.graphics.rectangle('fill',-cs.pan[1],-cs.pan[2],project.res.x,project.res.y)
	
	if cs.gridScale and cs.gridScale > 0 then
		love.graphics.setLineWidth(1)
		local s = cs.gridScale
		
		love.graphics.setColor(math.abs(bgc.r/255 - 0.15),math.abs(bgc.g/255 - 0.15),math.abs(bgc.b/255 - 0.15), 1)
		
		local offsetX = -cs.pan[1] % s
		local offsetY = -cs.pan[2] % s
		
		for x = offsetX, 600, s do
			love.graphics.line(x, 0, x, 360)
		end
		
		for y = offsetY, 360, s do
			love.graphics.line(0, y, 600, y)
		end
	end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = '''function GameManager:drawHud()'''
position = "after"
payload = '''
if not cs.drawHud then
	return
end
'''
match_indent = true
